//Configuration for YTPlayer
//Automatically Generated by PhantomBot at Startup
//Do NOT Modify! Overwritten when PhantomBot is restarted!
var playerPort = 25003;
var channelName = "eichiviech1990";
var auth="ntWEdjp82hfBJCaqj63Sb0iasrTf0N";
var http="http://";
function getPlayerPort() { return playerPort; }
function getChannelName() { return channelName; }
function getAuth() { return auth; }
function getProtocol() { return http; }
